plugins {
    id 'org.asciidoctor.jvm.convert' version '4.0.2'
}

repositories {
    mavenCentral()
}

// ############################################################################
// Allgemeine Definitionen
defaultTasks 'asciidoctor'
// ############################################################################

// ############################################################################
asciidoctor {
    // Eingabe- und Ausgabe-Verzeichnisse
    sourceDir = file('adocs')
    outputDir = file('html')

    // Nur die gewünschten Dateien bauen
    sources {
        include 'usermanual.adoc'
        include 'developers-guide.adoc'
        include 'Arbeitsdienste.adoc'
    }
    baseDirFollowsSourceDir()

    // Ausgabeformat HTML5
    outputOptions {
        backends = ['html5']
    }

    // Optionale Attribute (z.B. Icons, Tabellen, etc.)
    attributes(
        'stylesdir'     : '../stylesheets',
        'stylesheet'    : 'riak.css',
        'source-highlighter': 'rouge',
        'toc': 'left',
        'toclevels': '3',
        'sectanchors': 'true'
    )
}
// ############################################################################
