= ADHelper - Entwicklerhandbuch
Mathias-H. Weber <mhw@teambaltic.de>
v2.0, 26. April 2020
:doctype: book
:encoding: utf-8
:lang: de
:toc: left
:toclevels: 4
:last-update-label: Erstellt mit Asciidoctor v{asciidoctor-version} : Zuletzt geändert:
// Ohne dem haben die "Admonition"-Blocks keine Icons!
:icons: font
:numbered:
:source-highlighter: highlightjs
// Deutsche Überschriften:
:toc-title: Inhaltsverzeichnis
:figure-caption: Abbildung
:table-caption: Tabelle
:chapter-label: Kapitel
:appendix-caption: Anhang
//:example-caption!:
// Jeder Abschnitt bekommt automatisch einen Anker:
:sectanchors:
// Makro "kbd:" aktivieren:
:experimental:

In dieser Dokumentation sind alle Entwicklungsaspekte zum Programm `ADHelper` festgehalten. Sie soll sicherstellen, dass es auch nicht eingeweihten Personen möglich ist, das Programm zu pflegen und ggfs. weiterzuentwickeln.

Eine gute erste Quelle für einen Überblick ist die Datei https://raw.githubusercontent.com/baltic-mh/ADHelper/master/misc/Dokumentation/Dokumentation.txt[Dokumentation.txt] im Repository des Projektes.

== Java

Das Projekt ist mit ORACLE JAVA 8 kompilierbar. Ob spätere Versionen oder andere Varianten funktionieren, habe ich nicht ausprobiert.

== Git

Das Projekt ist auf GitHub gehostet.
Die Adresse des Repositories ist `https://github.com/baltic-mh/ADHelper.git`.

Es gibt aktuell zwei Branches `master` und `gh-pages`.
Der Branch `master` wird für die Software-Entwicklung benutzt und der Branch `gh-pages` für die Entwicklung der Dokumentation.


Es empfiehlt sich, dasselbe Repository zweimal in unterschiedliche Verzeichnis zu klonen (z.B. in die Verzeichnisse `ADHelper` und `ADHelper-Pages`), wobei pro Verzeichnis nur jeweils ein Branch geclont wird.
Auf diese Weise kann man ungestört an Dokumentation und Projekt gleichzeitig entwickeln, ohne die Branches wechseln zu müssen. 

////
==========================================================================
////
== Eclipse

Selbstverständlich kann jede beliebige Entwicklungsumgebung benutzt werden, wenn es sein muss auch `vi` ;-) . Ich nutze `Eclipse`.

=== Import

Das Projekt ist als  `Gradle`-Projekt aufgesetzt. Nachdem das Repository geclont worden ist, kann das Projekt in Eclipse importiert werden.

Damit Eclipse sich korrekt orientieren kann, ist einmal im Wurzelverzeichnis des Projektes die Gradle-Task aufzurufen:

```
./gradlew.bat eclipse
```

Nach dem ersten Import wird noch ein Compiler-Fehler moniert werden, weil die Java-Klasse `teambaltic.BuildConfig` nicht existiert. 
Die wird allerdings auch dynamisch erzeugt. Dazu muss man einmal die folgende Gradle-Task aufrufen:

```
./gradlew.bat assemble
```

Dabei merkt man auch gleich, ob ein gültiges JDK installiert und zugänglich ist. Wenn es hier zu Problemen kommt, muss man in der Regel die Environment-Variable `JAVA_HOME` korrekt setzen.

Danach muss in Eclipse der Arbeitsbereich noch einmal aktualisiert werden.

=== Ausführen des Programmes

WARNING: Bevor man das Programm ausführen kann, muss man erst einmal Daten zur Verfügung stellen, die das Programm bearbeiten kann.
Da Daten aber immer unter dem Datenschutz stehen, sind sie _nicht_ im Repository hinterlegt - und werden nur an besonders vertrauenswürdige Menschen verteilt!

Die Klasse mit der `main`-Methode ist `ADH_Application` im Paket `teambaltic.adhelper.gui`.


////
==========================================================================
////

== Build-Prozess mit Gradle

Der gesamte Build-Prozess wird über 
https://gradle.org/guides/[Gradle]
bewerkstelligt. Gradle selbst muss nicht installiert sein, im Repository ist ein sogenannter Wrapper, der das Notwendige bei Bedarf runterlädt.

Wenn ein neues Release erzeugt werden soll, ist der im folgenden beschriebene Prozess notwendig. Als Spickzettel dient die Datei `README.ReleaseErzeugung`, in der das Vorgehen in kurzer und prägnater Form beschrieben ist.

=== Anpassen der Versionsnummer

Die aktuelle Versionsnummer ist in der Datei `gradle.properties` hinterlegt. Die sieht in etwa so aus:

```
version = 1.17.1-SNAPSHOT
```

Wenn man nur eine Kleinigkeit am Programm geändert (ein kleiner Bugfix oder eine sonst nicht weiter auffällige Änderung), braucht man an der Versionsnummer gar nichts zu machen - die letzte Stelle ist bereits gegenüber der vorhergehenden Release-Erstellung um eins erhöht worden (im konkreten Fall wäre die neue Versionsnummer also 1.17.1 - der Zusatz `SNAPSHOT` wird bei einem Release entfernt).

Hat man spürbare Änderungen vorgenommen, sollte die mittlere Stelle um eins erhöht - und die letzte wieder auf Null gesetzt werden. Das sieht dann konkret so aus:

```
version = 1.18.0-SNAPSHOT
```

=== Beschreibung der Änderungen/Erweiterungen/Bugfixes seit dem letzten Release

Bei der Release-Erstellung wird eine Datei `ReleaseNotes.txt` automatisch erzeugt, die die forlaufende Änderungshistorie beinhaltet.
Damit das funktioniert, müssen die Modifikationen, die für dieses Release gemacht wurden, in der Datei `misc/build-res/ReleaseNotes-actual.txt` beschrieben werden.

```
###############################################################################
# ReleaseNotes der aktuellen Version
# Die einzelnen Änderungen/Neuerungen müssen mit einer Kategorie beginnen.
# Die Kategorie muss in eckigen Klammern stehen.
# Danach muss in derselben Zeile noch Text stehen
# Übliche Kategorien sind:
#[NEU]      Für ein neues Feature
#[BUGFIX]   Für einen behobenen Fehler
#[ÄNDERUNG] Für ein geändertes Verhalten
#
# Zeilen, die mit # oder // anfangen, werden ignoriert.
# Es muss eine Zeile geben, die mit "//RELEASE:" anfängt gefolgt von der
# Release-Nummer des anstehenden Releases.
# Die Release-Nummer wird aus der Versionsnummer gebildet:
#   Versionsnummer 1.2.3 => Release-Nummer: 1002003
#   Versionsnummer 2.0.0 => Release-Nummer: 2000000
# Allgemeine Bildungsregel:
#    Versionsnummer: Major.Minor.Build
# => Release-Nummer:
#       (Major)(Minor, dreistellig mit führenden 0en)(Build, dreistellig mit führenden 0en)
###############################################################################
//RELEASE: 1018000
###############################################################################
[NEU] Die Konfigurationsdatei "VereinsDaten" wird bei Abschluss des Zeitraumes mit in das zugehörige Verzeichnis kopiert
```

Hier ist die Zeile, die mit `//RELEASE:` beginnt, entscheidend.
Die darauf folgende Nummer ist die Release-Nummer, die an die Versionsnummer  (siehe vorhieriger Schritt) anzupassen ist.
Wie man von der Versionsnummer auf die zugehörige Release-Nummer kommt, ist im Kommentar in der Datei exemplarisch beschrieben.

Nach der letzten Zeile mit den vielen Lattenzäunen (#) stehen eventuell noch die Informationen aus der letzten Release-Erstellung.
Die werden gelöscht und dafür die Neuerungen für dieses Release beschrieben.
Die Syntax dazu ist ebenfalls im Kommentar beschrieben.

Der obere Teil der automatisch erzeugte ReleaseNotes-Datei sieht dann später so aus:

```
================================================================================
Release: 1018000	Version: 1.18.0	Datum: 2020-04-26
[NEU] Die Konfigurationsdatei "VereinsDaten" wird bei Abschluss des Zeitraumes mit in das zugehörige Verzeichnis kopiert
================================================================================
Release: 1017000	Version: 1.17.0	Datum: 2020-04-25
[ÄNDERUNG] Im Log-Fenster laufen die Meldungen nun von oben nach unten!
[NEU] Lokale Konfigurationsdateien können nun auch nur einzelne Werte enthalten
[NEU] Warnung, wenn lokale Konfigurationsdatei Daten überschreibt

================================================================================
Release: 1016000	Version: 1.16.0	Datum: 2020-04-25
[NEU] Verzeichnis "Obsolete" behält nur noch die 5 neuesten Elemente
[NEU] Es werden nur noch die 4 neuesten Abrechnungszeiträume dargestellt
================================================================================
Release: 1015001	Version: 1.15.1	Datum: 2020-04-24
[BUGFIX] NPE behoben für Pflichtstunden spezifisch je Halbjahr
================================================================================
Release: 1015000	Version: 1.15.0	Datum: 2020-04-24
[NEU] Pflichtstunden nun spezifisch je Halbjahr angebbar
[BUGFIX] Auslesen der Update-URL aus Online-Datei wiederbelebt

...
```

=== Git-Push

Alle geänderten Dateien müssen in GIT committed und gepusht sein.

=== Erzeugen des Releases

Durch Aufruf der Gradle-Task
```
gradlew release -Prelease.useAutomaticVersion=true
```

gerät eine Maschinerie in Gange, die einem den Atem verschlägt!
Hier muss man kräftig die Daumen drücken, dass alles gut geht - oder sonst eben Ursachenforschung betreiben ;-)
Danach hat man ein neues Executable erstellt, es auf den Download-Server übertragen, die Versionsnummer erhöht und noch vieles mehr.

=== Überprüfen, ob alles chicko ist!

Hier sollte man sich das Executable mal manuell vom Download-Server kopieren und auf Herz und Nieren prüfen. Wenn es schwächelt, muss man eben noch mal ran!

=== Release zum Download freigeben 

Das Erzeugen und Hochladen des Releases auf den Download-Server führt noch nicht dazu, dass das ein älteres Programm, dass auf einem beliebigen Client-Rechner gestartet wird, das neue Release runterlädt.
Dazu ist noch eine letzte Freigabe notwendig.
Erst wenn man sich davon überzeugt hat, dass das neu erzeugte Executable auch einwandfrei tut, sollte man diese Freigabe erteilen.

Die Freigabe erfolgt durch den Aufruf der Gradle-Task
```
gradlew ssh_release
```



[WARNING]
====
Damit das Erzeugen eines Release problemlos funktioniert, müssen
folgende Voraussetzungen erfüllt sein:

. Die SSH-Konfiguration muss korrekt aufgesetzt sein.
Aufzuführen, was das in Einzelnen bedeutet, führt an dieser Stelle zu weit.
Der Hinweis mag vorerst genügen.

. Die beiden SSH-Schlüsseldateien `id_rsa.kvk@syniphos` und `id_rsa.kvk@syniphos.pub` müssen im Verzeichnis `.\ADHelper\misc\build-res\` vorliegen. 
Da es sich bei diesen Dateien um Schlüssel handelt, die Zugriff auf den Server gewähren, sind sie nicht im Repository gespeichert!
Die Dateien werden auf Anfrage bereit gestellt.
====

== Bugtracking

Zur Fehlerverfolgung wird
https://syniphos.i234.me/mantisbt/login_page.php[Mantis]
eingesetzt.

Für den direkten Zugang aus Eclipse heraus gibt es einen 
https://marketplace.eclipse.org/content/mylyn-mantis-connector[Mylyn-Connector], 
den man direkt aus dem MarketPlace von Eclipse installieren kann. 

IMPORTANT: Leider ist dieses Plugin nicht mehr mit der Eclipse-Version 2020-03 kompatibel :-|

////
==========================================================================
////

== Konfiguration

Alle Konfigurationsdateien, die das Programm einliest, werden als Property-Dateien interpretiert und müssen eine entsprechende Syntax aufweisen.

Die erste Konfigurationsdatei, die eingelesen wird, ist `<Installationsverzeichnis>\ADHelper.properties`.
Hier ist das Wurzelverzeichnis angegeben, in dem nach weiteren Daten gesucht wird. Der Inhalt sieht beispielhaft so aus:

```
# Dies sind Properties, die zum Start der Applikation ADHelper eingelesen werden
FOLDERNAME_ROOT=Arbeitsdienstabrechnungen-Test
```

Durch Angabe unterschiedlicher Werte für `FOLDERNAME_ROOT` kann man unterschiedliche Testszenarien realisieren und die _echten_ Daten unberührt lassen.

Für alle weiteren Einstellungen sind Default-Werte fest in das Programm einkompiliert.
Die Werte stehen im Entwicklungssystem in `.properties`-Dateien im Verzeichnis `ADHelper\src\main\resources\`.

Die darin enthaltenen Werte können zur Laufzeit überschrieben werden, indem man eine gleichnamige Datei im Ordner `<Installationsverzeichnis>\<FOLDERNAME_ROOT>\Einstellungen` platziert.
In den jeweiligen Dateien müssen nur die Werte enthalten sein, die von den Default-Werten abweichen sollen - für alle anderen Parameter werden die eingebauten Werte verwendet.
Dadurch ist es leicht möglich, einige Konfigurationsparameter temporär an spezielle Bedürfnisse anzupassen.

[WARNING]
====
Wenn ein Datei im oben genannten Verzeichnis existiert, überschreibt sie die ins Programm eingebrannten Werte! 
Daher sollte dies ausdrücklich nur in Ausnahmefällen und temporär erfolgen!
Zur Erinnerung wird im Log-Fenster eine Warnung ausgegeben, wenn eine lokale Datei einen Wert überschreibt.
Die lokale Datei ist bei erster Gelegenheit wieder zu löschen!
====

=== Applikationseinstellungen

.Applikationseinstellungen
[cols="10,10,80",options="header"]
|=======================
| PARAMETER                     | Default-Wert              | Bemerkung
| FOLDERNAME_ROOT               | .                         |
| FOLDERNAME_DATA               | Daten                     |
| FOLDERNAME_SETTINGS           | Einstellungen             | 
| FOLDERNAME_SANDBOX            | Sandkiste                 | 
| FOLDERNAME_SECRETS            | ssh                       | 
| FILENAME_BASEINFO             | BasisDaten.csv            |
| FILENAME_WORKEVENTS           | Arbeitsdienste.csv        | 
| FILENAME_ADJUSTMENTS          | Gutschriften.csv          | 
| FILENAME_BALANCES             | Guthaben.csv              | 
| FILENAME_BALANCEHISTORY       | GuthabenVerlauf.csv       | 
| FILENAME_USERDATA             | BenutzerDaten.properties  | 
| FILENAME_CLUBDATA             | VereinsDaten.properties   | *Wichtige Konfigurationdatei*
| FILENAME_FINISHED             | Abgeschlossen.txt         | 
| FILENAME_UPLOADED             | Hochgeladen.txt           |
| FILENAME_UISETTINGS           | UISettings.properties     |
| FILENAME_REMOTEACCESSDATA     | ServerZugangsDaten.properties | 
| FILENAME_CRYPT_PRIV           | private.key               | 
| FILENAME_CRYPT_PUBL           | public.key                |
| CYCLETIME_SINGLETONWATCHER    | 5000                      |
| MAXNUM_KEEPOBSOLETEFOLDERS    | 5                         | Maximale Zahl von Backups im Verzeichnis `Obsolete`
| MAXNUM_PERIODSTOCONSIDER      | 4                         | Maximale Zahl der im Programm dargestellten Abrechnungszeiträume
|=======================


=== Vereinsdaten

[IMPORTANT]
====
Die Vereinsdaten geben die Randbedingungen wieder, die in unserem Verein für die Ableistung von Arbeitsdiensten bestehen.
Sie sind in aller Regel durch Vorstandsbeschlüsse festgelegt.

Eine nicht authorisierte Änderung hieran bedeutet also, dass das Programm die Berechnung anders vornimmt, als vom Vorstand beschlossen!
====

Ort der Datei: `\src\main\resources\VereinsDaten.properties`.

Aktueller Inhalt (Stand April 2020):

.Vereinsdaten
[cols="10,10,80",options="header"]
|=======================
| PARAMETER                     | Default-Wert  | Bemerkung
| MIN_AGE_FOR_DUTY              | 16            | Mindestalter, ab dem Arbeitsdienstpflicht besteht
| MAX_AGE_FOR_DUTY              | 60            | Höchstalter, bis zu dem Arbeitsdienstpflicht besteht
| PROTECTION_TIME               | 6             | Anzahl der Monate, die man nach Vereinseintritt vom AD befreit ist
| DUTYHOURS_PER_PERIOD          | 3             | Anzahl Pflichtarbeitsstunden pro Abrechnungszeitraum
| DUTYHOURS_PER_PERIOD.2020_1   | 0             | Anzahl Pflichtarbeitsstunden im Abrechnungszeitraum 1. Halbjahr 2020 (wg. Corona)
| DUTYHOURS_PER_PERIOD.2020_2   | 6             | Anzahl Pflichtarbeitsstunden im Abrechnungszeitraum 2. Halbjahr 2020 (wg. Corona)
|=======================


==== Anmerkungen zu Stundenwerten spezifisch für bestimmte Abrechnungszeiträume

Nach unserer Satzung besteht die Pflicht zum Arbeitsdienst.
Der Vorstand hat die Anzahl der Pflichtstunden auf drei pro Halbjahr festgelegt. 
Wegen der Schwierigkeit im Rahmen der Corona-Krise im Jahr 2020 die üblichen gemeinsamen Arbeitsdienste anzusetzen, wurde beschlossen, die Aufteilung der jährlichen sechs Pflichtstunden auf die Halbjahre für 2020 aufzuheben.
In diesem Jahr müssen also weiterhin insgesamt sechs Stunden Arbeitsdienst geleistet werden, aber sie können über das gesamte Jahr verteilt werden, es müssen also im ersten Halbjahr nicht zwingend drei Stunden abgeleistet werden.

Es können nun Stundenwerte spezifisch für einen bestimmten Abrechnungszeitraum eingegeben werden. 
Die Syntax ist so, dass hinter dem Parameternamen ein Punkt folgen muss, dann das Jahr des Abrechnungszeitraumes, ein Unterstrich und schießlich eine "1" oder "2" für das entsprechende Halbjahr. Wird für einen bestimmten Abrechnungszeitraum kein spezifischer Wert gefunden, wird der Wert ohne Angabe eines Abrechnungszeitraumes genommen.

////
==========================================================================
////

include::includes/Dokumentation.adoc[]

////
==========================================================================
////

= Anhang
[appendix]
include::includes/Dateiformate.adoc[]
[appendix]
include::includes/Hosting.adoc[]

