= ADHelper - Entwicklerhandbuch
Mathias-H. Weber <mhw@teambaltic.de>
v1.0, 17. November 2016
:doctype: book
:encoding: utf-8
:lang: de
:toc: left
:toclevels: 4
:last-update-label: Erstellt mit Asciidoctor v{asciidoctor-version} : Zuletzt geändert:
// Ohne dem haben die "Admonition"-Blocks keine Icons!
:icons: font
:numbered:
:source-highlighter: highlightjs
// Deutsche Überschriften:
:toc-title: Inhaltsverzeichnis
:figure-caption: Abbildung
:table-caption: Tabelle
:chapter-label: Kapitel
//:example-caption!:
// Jeder Abschnitt bekommt automatisch einen Anker:
:sectanchors:
// Makro "kbd:" aktivieren:
:experimental:

== Java

Das Projekt ist mit ORACLE JAVA 8 kompilierbar. Ob spätere Versionen oder andere Varianten funktionieren, habe ich nicht ausprobiert.

== Git

Das Projekt ist auf GitHub gehostet: https://github.com/baltic-mh/ADHelper.git

Es gibt aktuell zwei Branches `master` und `gh-pages`.
Der Branch `master` wird für die Software-Entwicklung benutzt und der Branch `gh-pages` für die Entwicklung der Dokumentation.

Die Adresse des Repositories ist `https://github.com/baltic-mh/ADHelper.git`.

Es empfiehlt sich, dasselbe Repository zweimal in unterschiedliche Verzeichnis zu klonen (z.B. in die Verzeichnisse `ADHelper` und `ADHelper-Pages`), wobei pro Verzeichnis nur jeweils ein Branch geclont wird.
Auf diese Weise kann man ungestört an Dokumentation und Projekt gleichzeitig entwickeln kann, ohne die Branches wechseln zu müssen. 

////
==========================================================================
////
== Eclipse

Selbstverständlich kann jede beliebige Entwicklungsumgebung benutzt werden, wenn es sein muss auch `vi` ;-) . Ich nutze `Eclipse`.

=== Import

Das Projekt ist als  `Gradle`-Projekt aufgesetzt. Nachdem das Repository geclont worden ist, kann das Projekt in Eclipse importiert werden.

Damit Eclipse sich korrekt orientieren kann, ist einmal im Wurzelverzeichnis des Projektes die Gradle-Task aufzurufen:

```
./gradlew.bat eclipse
```

Nach dem ersten Import wird noch ein Compiler-Fehler moniert werden, weil die Java-Klasse `teambaltic.BuildConfig` nicht existiert. 
Die wird allerdings auch dynamisch erzeugt. Dazu muss man einmal die folgende Gradle-Task aufrufen:

```
./gradlew.bat assemble
```

Dabei merkt man auch gleich, ob ein gültiges JDK installiert und zugänglich ist. Wenn es hier zu Problemen kommt, muss man in der Regel die Environment-Variable `JAVA_HOME` korrekt setzen.

Danach muss in Eclipse der Arbeitsbereich noch einmal aktualisiert werden.

=== Ausführen des Programmes

WARNING: Bevor man das Programm ausführen kann, muss man erst einmal Daten zur Verfügung stellen, die das Programm bearbeiten kann.
Da Daten aber immer unter dem Datenschutz stehen, sind sie _nicht_ im Repository hinterlegt - und werden nur an besonders vertrauenswürdige Menschen verteilt!

Die Klasse mit der `main`-Methode ist `ADH_Application` im Paket `teambaltic.adhelper.gui`.


////
==========================================================================
////

== Build-Prozess mit Gradle


== Erzeugen eines neuen Releases

Wenn ein neues Release erzeugt werden soll, ist folgender Prozess notwendig:

. Eingabe der Änderungen/Erweiterungen/Bugfixes seit dem letzten Release +

****
Editieren der Datei => misc/build-res/ReleaseNotes-actual.txt
****

[start=2]
. Eventuell Anpassung der Datei +
****
Editieren der Datei => misc/Dokumentation/Dokumentation.txt
****

[start=3]
. Alle geänderten Dateien müssen in GIT committed und gepusht sein.

[start=4]
. Aufruf der Gradle-Task
****
gradlew release -Prelease.useAutomaticVersion=true
****

[start=5]
. Überprüfen, ob alles chicko ist!


[start=6]
. Release zum Download freigeben durch Aufruf der Gradle-Task +
****
gradlew ssh_release
****

== Bugtracking

Zur Fehlerverfolgung wird
http://www.mantisbt.org/index.php[Mantis]
eingesetzt.

Für den direkten Zugang aus Eclipse heraus gibt es einen 
https://marketplace.eclipse.org/content/mylyn-mantis-connector[Mylyn-Connector], 
den man direkt aus dem MarketPlace von Eclipse installieren kann.

////
==========================================================================
////

== Spezielle Themen

=== Pflichtstunden spezifisch für ein Halbjahr angeben

Nach unserer Satzung besteht die Pflicht zum Arbeitsdienst.
Der Vorstand hat die Anzahl der Pflichtstunden auf drei pro Halbjahr festgelegt. 
Wegen der Schwierigkeit im Rahmen der Corona-Krise im Jahr 2020 die üblichen gemeinsamen Arbeitsdienste anzusetzen, wurde beschlossen, die Aufteilung der jährlichen sechs Pflichtstunden auf die Halbjahre aufzuheben. Im Jahr 2020 müssen also weiterhin insgesamt sechs Stunden Arbeitsdienst geleistet werden, aber diese können über das gesamte Jahr verteilt werden, es müssen also im ersten Halbjahr nicht zwingend drei Stunden abgeleistet werden.

Im Programm ist das berücksichtigt worden, indem die Pflichtstunden pro Halbjahr nun nicht mehr konstant mit drei angenommen werden, sondern man sie für jedes Halbjahr spezifisch definieren kann.

Das geschieht durch Eintragen entsprechender Werte in die Datei `\src\main\resources\VereinsDaten.properties`. Hier die Angaben ihres aktuellen Inhaltes (Stand April 2020):

```
# Mindestalter ab dem Arbeitsdienstpflicht besteht
MIN_AGE_FOR_DUTY=16
# Höchstalter bis zu dem Arbeitsdienstpflicht besteht
MAX_AGE_FOR_DUTY=60
# Anzahl der Monate, die man nach Vereinseintritt vom AD befreit ist:
PROTECTION_TIME=6
# Anzahl Pflichtarbeitsstunden pro Abrechnungszeitraum
DUTYHOURS_PER_PERIOD=3
# Anzahl Pflichtarbeitsstunden im Abrechnungszeitraum 1. Halbjahr 2020 (Corona)
DUTYHOURS_PER_PERIOD.2020_1=0
# Anzahl Pflichtarbeitsstunden im Abrechnungszeitraum 2. Halbjahr 2020 (Corona)
DUTYHOURS_PER_PERIOD.2020_2=6
``` 

Sollte erneut eine Situation eintreten, in der vom Standard abgewichen werden soll, ist diese Datei entsprechend zu ändern und eine neue Version des Programmes zu erzeugen. Es ist bewusst darauf verzichtet worden, eine interaktive Eingabe der Pflichtstunden über das Programm zu implementieren.

////
==========================================================================
////

include::includes/Dokumentation.adoc[]

////
==========================================================================
////

= Anhang

include::includes/Dateiformate.adoc[]

