== Dokumentation

Die Dokumentation des Projektes ist im 
http://asciidoctor.org/[AsciiDoctor-Format]
erstellt.

Als Hilfsmittel zum Editieren der +.adoc+-Dateien empfehle ich 
http://asciidocfx.com/[AsciiDocFX].

Die Dokumentation ist wie das Projekt selbst auf GitHub gehostet.
Die Adresse des Repositories ist `https://github.com/baltic-mh/ADHelper.git`.

Die Dokumenation ist schlicht auf dem dedizierten Branch `gh-pages` des Projektes abgelegt.

=== Erstellen einer neuen Version

Nachdem der Inhalt in den zugehörigen +.adoc+-Dateien modifiziert worden ist, muss im Wurzelverzeichnis die Gradle-Task aufgerufen werden:

``` 
./gradlew.bat asciidoctor
``` 

Die durch diesen Build-Lauf erzeugten HTML-Dateien landen im Verzeichis `ADHelper-Pages\build\docs\html5\`.

Wenn man mit dem Ergebnis zufrieden ist, kann man die HTML-Dateien an den endgültigen Ort (ADHelper-Pages\html) kopieren, indem man die folgende Gradle-Task aufruft:

``` 
./gradlew.bat copyArtifacts
``` 

Natürlich kann man auch gleich die letztgenannte Task aufrufen - dann werden beide Schritte auf einmal erledigt. Oder man ruft ganz einfach

``` 
./gradlew.bat
``` 

auf - denn mittlerweile habe ich rausgefunden, wie man eine Default-Task definiert!

Wenn dann alles zur Zufriedenheit ist, kann man die geänderten Dateien mit Git ins Repository hochladen - und von dort werden sie dann automatisch aufgerufen, wenn man über den Menüpunkt kbd:[Hilfe] die Dokumentation aufruft.


=== Asciidoctor Links


- link:http://asciidoctor.org/[Asciidoctor]
- link:http://asciidoctor.org/docs/user-manual/[User-Manual]
- link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[Syntax-Quick-Referenz]
- link:http://powerman.name/doc/asciidoc[Cheat-Sheets]
- link:http://asciidoctor.org/docs/asciidoc-writers-guide/[Writer's Guide]
- link:https://leanpub.com/awesomeasciidoctornotebook/read[Awesome Asciidoctor Notebook]
- link:http://asciidoctor.org/docs/asciidoctor-diagram/[Asciidoctor-Diagram]
- link:http://asciidoctor.org/docs/asciidoctor-gradle-plugin/[Getting Started with the Asciidoctor Gradle Plugin]
- link:https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-title-page[Asciidoctor PDF Theming Guide]